apiVersion: apps/v1  
kind: Deployment
metadata:
  name: demucs-worker 
spec:
  selector:
    matchLabels:
      app: demucs-worker  
  replicas: 1
  template:
    metadata:
      labels:
        app: demucs-worker 
    spec:
      containers:
      - name: worker-container 
        image: vankudremanish/demucs-worker:latest 
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 5000  
        env:
        - name: REDIS_HOST
          value: "redis"  
        - name: REDIS_PORT
          value: "6379"
        - name: FLASK_HOST
          value: "0.0.0.0"  
        - name: FLASK_PORT
          value: "5000"  
        - name: MINIO_HOST
          value: "minio-proj.minio-ns.svc.cluster.local:9000" 
